samples: ucaip sample batch 2 of 6
googleapis/java-aiplatform pull request #15
Opened 2020-09-30 04:39 UTC by munkhuushmgl

batch 2 of 6

2020-09-30 12:26 UTC, stephaniewang526 commented
Looks like environment variable `UCAIP_PROJECT_ID` from testing project. Please set it in Secret Manager and re-run ITs. Thanks.

2020-09-30 21:06 UTC, stephaniewang526 requested changes

2020-09-30 21:06 UTC, stephaniewang526 commented on samples/snippets/src/main/java/aiplatform/ImportDataImageClassificationSample.java
> +      System.out.format("Import Data Image Classification Response: %s\n", importDataResponse);
Can you verify that you dont need to call the `toString` method here? Printing out the object signature is probably not very useful.

2020-09-30 21:06 UTC, stephaniewang526 commented on samples/snippets/src/main/java/aiplatform/ImportDataImageObjectDetectionSample.java
> +      System.out.format("Import Data Image Object Detection Response: %s\n", importDataResponse);
Same as above -- consider calling `toString()`

2020-09-30 21:06 UTC, stephaniewang526 commented on samples/snippets/src/main/java/aiplatform/ImportDataVideoObjectTrackingSample.java
> +      System.out.format("Import Data Video Object Tracking Response: %s\n", importDataResponse);
Same as above -- consider calling `toString()`.

2020-09-30 21:54 UTC, munkhuushmgl commented on samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineImageObjectDetectionSample.java
> +      List<Any> detailsList = status.getDetailsList();
I think it should be deleted.

2020-09-30 21:59 UTC, munkhuushmgl commented on samples/snippets/src/main/java/aiplatform/DeleteBatchPredictionJobSample.java
> +      Empty deleteResponse = operationFuture.get(300, TimeUnit.SECONDS);
I just checked response, and its empty object. nothing being printed out of the response.
I will delete this response object.

2020-10-01 03:00 UTC, stephaniewang526 approved these changes

2020-11-06 19:54 UTC, merged