feat: updates library for v1 service
googleapis/java-aiplatform pull request #157
Opened 2021-02-05 22:38 UTC by telpirion

Updates the library with v1 service types and enhanced types.

2021-02-19 19:18 UTC, chingor13 requested changes
One small change

2021-02-19 19:18 UTC, chingor13 commented on pom.xml
> +        <version>0.2.1-SNAPSHOT</version><!-- {x-version-update:grpc-google-cloud-aiplatform-v1:current} -->
Please restore this one. When the library is promoted to 1.0.0, the v1beta1 artifacts will stay at 0.x

```suggestion
        <version>0.2.1-SNAPSHOT</version><!-- {x-version-update:grpc-google-cloud-aiplatform-v1beta1:current} -->
```

2021-02-19 19:19 UTC, chingor13 requested changes
One more thing: need to add the v1 entry to the root `versions.txt` as well

2021-02-20 00:19 UTC, chingor13 approved these changes

2021-02-22 22:49 UTC, lucaswadedavis approved these changes

2021-02-23 21:05 UTC, merged